spring:
  main:
    banner-mode: "off"
  dataSource:
    driverClassName:  'com.mysql.jdbc.Driver'
    url: jdbc:mysql://localhost:3306/h3
    username: root
    password: 3toolong
  jpa:
    show-sql: false

